[package]
name = "multiple-body-problem"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
nalgebra = "0.33.2"
derive-new = "0.7.0"
uuid = "1.12.1"
bevy_2d_line = "0.1.3"
rand = "0.9.0"
bevy_prototype_lyon = "0.13.0"